spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: zhang123

sfk:
  maxSrcStrArySize: 5
  maxPlainTextLength: 15
  maxCipherTextLength: 45
  logicStr: 12,8#6,5
  encryptKeyString: KeyForEncryption
  scrambleKeyString: KeyForScramble